// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElRow: typeof import('element-plus/es')['ElRow']
    HelloWorld: typeof import('./../src/components/HelloWorld.vue')['default']
    IEpBell: typeof import('~icons/ep/bell')['default']
    IEpBellFilled: typeof import('~icons/ep/bell-filled')['default']
    IEpBottomLeft: typeof import('~icons/ep/bottom-left')['default']
    IEpCheck: typeof import('~icons/ep/check')['default']
    IEpClose: typeof import('~icons/ep/close')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

export {}
